### ISSUE TITLE
Setup Release Tooling

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-dotnet#25]
Setup Release Please:
https://github.com/googleapis/release-please/

**Comment by jskeet** [comment]
I don't have experience with release-please, but I can definitely set up the autorelease Kokoro job assuming there's a way of triggering that easily from release-please. It'll probably be next week before I can spend time on this though.

**Comment by grant** [comment]
I don't have any experience with that tool, but it's recommended and works fairly well with GitHub Actions as far as I can see.
Talked to Justin already and he recommends it.

**Comment by jskeet** [comment]
Yup, I'm fine with us using release-please to create the GitHub releases. It's just hooking that into Kokoro that I'll need to ask about internally. It's fine though - I think the two parts are pretty separable.

**Comment by jskeet** [comment]
There are three parts to releasing:

- Creating the release PR (sometimes done by release-please)
- Tagging the repo and creating the GitHub release (releasetool tag)
- Building and publishing the release itself via Kokoro

After consultation with Ben, I'm happy to do the first of these manually (but we need documentation). Release-please isn't a good fit because .NET project structures vary widely (even within our own repos).

The second part is ready to go, but I suspect we need the Kokoro job to run a [new version of releasetool](https://github.com/googleapis/releasetool/pull/280)

The third part is done, and was used to release 1.0.0-alpha06.

I'll leave this issue open until I've written docs for the first part, and we've validated that the second part works - but we've made significant progress.

**Comment by grant** [comment]
Sounds good. Feel free to close this whenever.
