### ISSUE TITLE
generate_protos.sh Unknown OSTYPE: darwin19

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-dotnet#7]
## Expected Behavior

Run `sh generate_protos.sh`

See some new folder/files somewhere.

## Actual Behavior

Output: `Unknown OSTYPE: darwin19`

**Comment by jskeet** [comment]
Given that `generate_protos.sh` is only expected to be run by developers within this repo, which currently just means "me", and I don't have a Mac to even test it on, I'd rather not put any time into this.

I could change the error message to "Operating system not supported for generation: darwin19" but I don't see practical benefits in trying to guess what will work for this scenario.

Grant, if you're using a Mac and want to get this working, that's fine and you can raise a PR for it - but I don't want to have untested code in there (or spend ages trying to work out how I *can* test this) for practical actual benefit. Assigning to you to either fix if you definitely want to be able to run this on a Mac, or close otherwise. (In the meantime, it should work fine on Linux...)

**Comment by grant** [comment]
Jon, we just give more instructions? What are the prerequisites?
I'll SSH into a different machine, that's fine. Is that all that's needed?

We can't just have you as the single point of failure.
As we discussed, I'm trying to get this working for .NET and duplicate across other languages.

**Comment by jskeet** [comment]
I'm happy to put more effort into READMEs and things later, but there's a significant urgency for getting bits published, and adding documentation for the process doesn't help that.

Just looking at the shell script makes it fairly clear that it works on Linux and Windows. The script is pretty copiously commented - I really wouldn't expect it to be a blocker for other languages.
